# Site settings
title: Andres Jordan (ajordan)
person_name: Andrés Jordán
research_name: Research
person_nickname: ajordan
email: nwbeqna@nfgeb.chp.py
mailto: znvygb:nwbeqna@nfgeb.chp.py
description: "Astrophysics Professor  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Exoplaneteer"
baseurl: "" # the subpath of your site, e.g. /blog/
hostname: andres-jordan.github.io # used to determine if google analytics should be triggered
url: http://andres-jordan.github.io/ # the base hostname & protocol for your site
permalink: /:title/

prev_url: ../
blog_url: http://andres-jordan.github.io/
research_base: research/
research_url: research/index.html
cv_url: shortcv.pdf
twitter_username: astrojor
github_username: andres-jordan

# Build settings
markdown: kramdown
